In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

Using TensorFlow backend.


In [3]:
print("Initial Feature Names: \n ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'\n 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum'] \n [0,6,7,8,9,10,12,13,15,16,17,18,19,20]"))

Initial Feature Names: 
 ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'
 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum'] 
 [0,6,7,8,9,10,12,13,15,16,17,18,19,20]


In [4]:
# Import all tradable stocks of 2015 (features X)
import numpy as np
import csv
data = list(csv.reader(open('/Users/kimardenmiller/dropbox/tensorflow/data/x2015_noFinance.csv')))
feature_data = np.asarray(data)
# print('Example Stock with All Features: ', '\n', feature_data[0:2,:], ' ...')  # First stock in X
# First stock in X with selected features
selected_features = feature_data[:,[0, 6, 8, 9, 13, 17, 18, 20]]  
# print('Example Stock with Selected Features: ', '\n', selected_features[0:2,:], ' ...')
# X with selected features and labels & blanks removed
x_data_features = selected_features[1:, :]
x_data_features[x_data_features == ''] = 0.0
x_data = x_data_features
selected_feature_labels = selected_features[0, 1:]
print('Selected Feature Names: \n', selected_feature_labels)
print('First few Stocks with Features, no Lables: ', '\n', x_data[0:2, :], ' ...')
print(np.size(x_data[:, 0]), 'Stocks by', np.size(x_data[0, :]), 'Features')

Selected Feature Names: 
 ['total yield' 'roic v2' 'book price' 'fcf yield' 'total return'
 'spitz roic' 'momentum']
First few Stocks with Features, no Lables:  
 [['DD' '0.03' '0.19' '0.16' '0.03' '0.09' '0.18' '0.93']
 ['DOW' '0.04' '0.13' '0.42' '0.03' '0.1' '0.13' '0.94']]  ...
1436 Stocks by 8 Features


In [4]:
# Test for Panda Import Fail
import numpy as np
import csv
data = list(csv.reader(open('/Users/kimardenmiller/dropbox/tensorflow/data/x2015_noFinance.csv')))
csv_data = np.asarray(data)
print('CSV shape: ', csv_data.shape)
print('Example CVS Stock with All Features: ', '\n', csv_data[0:2, :], ' ...')  # First stock in X
print('Zero lines: \n', csv_data[csv_data == ''])

import pandas
x_import = pandas.read_csv('/Users/kimardenmiller/dropbox/tensorflow/data/x2015_noFinance.csv', header=0)
print('Panda shape: ', x_import.shape)
# print('Example Panda Pre Stock with All Features: ', '\n', x_import)  # First stock in X
x_import.fillna(value=0)
# print('Panda Nulls: ', x_import[x_import > 0])
panda_data = x_import.values
print('Panda shape: ', x_data_values.shape)
print('Example Panda Stock with All Features: ', '\n', panda_data[0:2, :], ' ...')  # First stock in X

# First stock in X with selected features
selected_features = panda_data[:, [0, 6, 8, 9, 13, 17, 18, 20]]  
# print('Example Stock with Selected Features: ', '\n', selected_features[0:2,:], ' ...')
# X with selected features and labels & blanks removed
x_data_features = selected_features[1:, :]
x_data_features[x_data_features == ''] = 0.0
x_data = x_data_features
selected_feature_labels = selected_features[0, 1:]
print('Selected Feature Names: \n', selected_feature_labels)
print('First few Stocks with Features, no Labels: ', '\n', x_data[0:2, :], ' ...')
print(np.size(x_data[:, 0]), 'Stocks by', np.size(x_data[0,:]), 'Features')
x_strings = x_data[:, 1:]  # take off tickers, as they can't be tensor'd
raw_X = x_strings.astype(np.float)  # convert strings to float
print('First few X Training Examples with', np.size(raw_X[0, :]), 'Selected Features: \n', raw_X[0:2, :], ' ...')

# A)  Standardize the X data (*** But this approach gives negatives, which is not good.)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(raw_X)
std_rescaledX = scaler.transform(raw_X)
# summarize transformed data
np.set_printoptions(precision=3, suppress=True)
print('Pre Standardizing: \n', raw_X[0:5, :])
print('After Standardizing: \n', std_rescaledX[0:5, :])

CSV shape:  (1437, 25)
Example CVS Stock with All Features:  
 [['Ticker' 'Company' 'score' 'Close' 'Market Cap' 'Change 1M' 'total yield'
  'ms debt' 'roic v2' 'book price' 'sic' 'price251ago' 'opInc' 'fcf yield'
  'dolVol' 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce'
  'momentum' 'Sector' 'Industry' 'Description' 'rebalance']
 ['DD' 'E.I. du Pont de Nemours' '0' '69.26' '58553545945.41' '0.46' '0.03'
  '11356000156.93' '0.19' '0.16' '16417999988.64' '64.86' '2892999992.35'
  '0.03' '183223497.72' '9514000033.31' '5531999915.68' '0.09' '0.18'
  '4452000010.73' '0.93' 'Basic Materials' 'Agriculture'
  'A science and technology based company' 'False']]  ...
Zero lines: 
 ['' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' 

Panda shape:  (1436, 25)


NameError: name 'x_data_values' is not defined

In [5]:
# Import best performing stocks of 2015 (y = 1)
import csv
data = list(csv.reader(open('/Users/kimardenmiller/dropbox/tensorflow/data/y201501_noFinancials.csv')))
y_data = np.asarray(data[1:])
print('First few Positive Examples: ', '\n', y_data[0:3, 0:5], ' ...')
# Find X and Y tickers
x_tickers = x_data[:, 0]
y_tickers = y_data[:, 0]
print('Total Y Tickers: ', np.size(y_tickers))
# Format Y to y = 1 (positive) and y = 0 (negative) examples 
true_false_mask = np.in1d(x_tickers, y_tickers)
y_mask = np.where(true_false_mask, 1, 0)
print('Total Positive Y Ticker Example Count: ', np.size(np.nonzero(y_mask)), )
print('Total Positive Y Ticker Example Count on x_tickers: ', np.size(x_tickers[np.nonzero(y_mask)]))
# Place dataset into input (X) and output (Y) variables
x_strings = x_data[:, 1:]  # take off tickers, as they can't be tensor'd
raw_X = x_strings.astype(np.float)  # convert strings to float
Y = y_mask        # Y uses the 0, 1 to show negative and positive examples
np.set_printoptions(precision=3, suppress=True)
print('First few X Training Examples with', np.size(raw_X[0, :]) , 'Selected Features: \n', raw_X[0:2, :], ' ...')

First few Positive Examples:  
 [['AAPL' 'Apple, Inc.' 'NASD' 'Technology' 'Computer Hardware']
 ['ABAX' 'ABAXIS, Inc.' 'NASD' 'Health Care' 'Medical Supplies']
 ['ABC' 'AmerisourceBergen Corp.' 'NYSE' 'Consumer Staples'
  'Drug Retailers']]  ...
Total Y Tickers:  237
Total Positive Y Ticker Example Count:  119
Total Positive Y Ticker Example Count on x_tickers:  119
First few X Training Examples with 7 Selected Features: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]]  ...


In [7]:
# A)  Standardize the X data (*** But this approach gives negatives, which is not good.)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(raw_X)
std_rescaledX = scaler.transform(raw_X)
# summarize transformed data
np.set_printoptions(precision=3, suppress=True)
print('Pre Standardizing: \n', raw_X[0:5, :])
print('After Standardizing: \n', std_rescaledX[0:5, :])

Pre Standardizing: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]
 [ 0.09  0.2   0.1   0.04  0.1   0.2   0.88]
 [ 0.04  0.13  0.21  0.04 -0.01  0.13  0.92]
 [ 0.03  0.16  0.16  0.04  0.08  0.16  0.96]]
After Standardizing: 
 [[-0.424 -0.071 -0.563 -0.003 -0.024 -0.031  0.587]
 [-0.233 -0.122 -0.059 -0.003 -0.024 -0.053  0.662]
 [ 0.72  -0.062 -0.68   0.048 -0.024 -0.022  0.211]
 [-0.233 -0.122 -0.466  0.048 -0.025 -0.053  0.512]
 [-0.424 -0.097 -0.563  0.048 -0.024 -0.04   0.813]]


In [5]:
# B)  Rescale data (between 0 and 1)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
range_rescaledX = scaler.fit_transform(raw_X)
# summarize transformed data
np.set_printoptions(precision=3)
print('Pre scaling: \n', raw_X[0:5, :])
print('After scaling: \n', range_rescaledX[0:5, :])

Pre scaling: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]
 [ 0.09  0.2   0.1   0.04  0.1   0.2   0.88]
 [ 0.04  0.13  0.21  0.04 -0.01  0.13  0.92]
 [ 0.03  0.16  0.16  0.04  0.08  0.16  0.96]]
After scaling: 
 [[ 0.049  0.006  0.436  0.484  0.028  0.028  0.922]
 [ 0.066  0.004  0.457  0.484  0.028  0.028  0.933]
 [ 0.148  0.006  0.431  0.486  0.028  0.029  0.867]
 [ 0.066  0.004  0.44   0.486  0.028  0.028  0.911]
 [ 0.049  0.005  0.436  0.486  0.028  0.028  0.956]]


In [5]:
# C)  Normalize data (length of 1)
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(raw_X)
normalizedX = scaler.transform(raw_X)
# summarize transformed data
np.set_printoptions(precision=3)
print('Pre scaling: \n', raw_X[0:5, :])
print('After scaling: \n', normalizedX[0:5, :])

Pre scaling: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]
 [ 0.09  0.2   0.1   0.04  0.1   0.2   0.88]
 [ 0.04  0.13  0.21  0.04 -0.01  0.13  0.92]
 [ 0.03  0.16  0.16  0.04  0.08  0.16  0.96]]
After scaling: 
 [[ 0.03   0.193  0.163  0.03   0.091  0.183  0.945]
 [ 0.038  0.124  0.399  0.029  0.095  0.124  0.894]
 [ 0.096  0.213  0.106  0.043  0.106  0.213  0.936]
 [ 0.042  0.135  0.218  0.042 -0.01   0.135  0.955]
 [ 0.03   0.159  0.159  0.04   0.08   0.159  0.957]]


In [6]:
# create model
model = Sequential()
model.add(Dense(7, input_dim=7, init='uniform', activation='relu'))
model.add(Dense(7, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

In [7]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', 'fbeta_score'])

# Set any Feature Normalization
X = raw_X  # Choices: std_rescaledX, range_rescaledX, normalizedX or just raw_X

print('Pre Feature Normalization: \n', raw_X[0:5, :])
print('After Feature Normalization: \n', X[0:5, :])

Pre Feature Normalization: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]
 [ 0.09  0.2   0.1   0.04  0.1   0.2   0.88]
 [ 0.04  0.13  0.21  0.04 -0.01  0.13  0.92]
 [ 0.03  0.16  0.16  0.04  0.08  0.16  0.96]]
After Feature Normalization: 
 [[ 0.03  0.19  0.16  0.03  0.09  0.18  0.93]
 [ 0.04  0.13  0.42  0.03  0.1   0.13  0.94]
 [ 0.09  0.2   0.1   0.04  0.1   0.2   0.88]
 [ 0.04  0.13  0.21  0.04 -0.01  0.13  0.92]
 [ 0.03  0.16  0.16  0.04  0.08  0.16  0.96]]


In [8]:
# Fit the model
model.fit(X, Y, nb_epoch=600, batch_size=10, verbose=0)
# model.fit(normalizedX, Y, nb_epoch=300, batch_size=10) # Change back to 150 after testing

In [9]:
# evaluate the model
scores = model.evaluate(X, Y)
# scores = model.evaluate(normalizedX, Y)
print('\n', "%s: %.2f%%" % (model.metrics_names[0], scores[0]*100))
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
print("%s: %.2f%%" % (model.metrics_names[2], scores[2]*100))
# print(model.metrics_names)
# print(scores)

  32/1436 [..............................] - ETA: 1s

 256/1436 [====>.........................] - ETA: 0s

 480/1436 [=========>....................] - ETA: 0s

 704/1436 [=============>................] - ETA: 0s

 928/1436 [==================>...........] - ETA: 0s

1184/1436 [=======================>......] - ETA: 0s

1436/1436 [==============================] - 0s     



 loss: 26.62%
acc: 91.71%
fbeta_score: nan%


In [10]:
# calculate predictions
predictions = model.predict(X)
# predictions = model.predict(normalizedX)
np.set_printoptions(precision=3, suppress=True)
print('Fist 100 Predictions: ', '\n', predictions[0:100, 0])
print('Rows in Prediction: ', np.size(predictions[:, 0]))
positive_predictions = np.sum(predictions[:, 0] > .5)
print('Positive Predictions: ', positive_predictions)
print('Positive Prediction Pointers: ', '\n', np.where(predictions[:, 0] > .5))
picks_data = feature_data[1:,:]
print('Positive Prediction Tickers: ', '\n', picks_data[np.where(predictions[:, 0] > .5), 0:2][0])
print('Positive Prediction Ground Truth: ', '\n', Y[np.where(predictions[:, 0] > .5)] )
accurate_predictions = np.size(np.nonzero(Y[np.where(predictions[:, 0] > .5)]))
print('Accuracy of Positive Predictions: ', '\n', "%.1f%%" % ((accurate_predictions / positive_predictions) * 100 if positive_predictions > 0 else 0))

Fist 100 Predictions:  
 [ 0.102  0.085  0.142  0.092  0.094  0.096  0.131  0.186  0.098  0.047
  0.099  0.064  0.088  0.084  0.018  0.118  0.084  0.161  0.077  0.079
  0.036  0.116  0.039  0.107  0.086  0.109  0.051  0.099  0.071  0.071
  0.037  0.127  0.057  0.109  0.168  0.022  0.096  0.037  0.04   0.04   0.1
  0.035  0.085  0.077  0.082  0.098  0.021  0.099  0.102  0.066  0.086
  0.086  0.031  0.042  0.243  0.07   0.091  0.028  0.066  0.058  0.084
  0.105  0.159  0.103  0.088  0.119  0.08   0.096  0.101  0.11   0.087
  0.079  0.025  0.021  0.046  0.104  0.     0.072  0.067  0.063  0.071
  0.122  0.082  0.068  0.092  0.     0.026  0.014  0.05   0.052  0.021
  0.051  0.05   0.085  0.038  0.077  0.075  0.     0.045  0.026]
Rows in Prediction:  1436
Positive Predictions:  2
Positive Prediction Pointers:  
 (array([1155, 1178]),)
Positive Prediction Tickers:  
 ['CHCT' 'GLW']
Positive Prediction Tickers:  
 [['CHCT' 'Community Healthcare']
 ['GLW' 'Corning']]
Positive Prediction Ground 