In [1]:
# Import all tradable stocks of 2015 (features X)
import numpy as np
import csv
data = list(csv.reader(open('../data/x2015.csv')))
feature_data = np.asarray(data)
# print('Example Stock with All Features: ', '\n', feature_data[0:2,:], ' ...')  # First stock in X
# First stock in X with selected features
selected_features = feature_data[:,[0,6,7,8,9,10,12,13,15,16,17,18,19,20]]  
# print('Example Stock with Selected Features: ', '\n', selected_features[0:2,:], ' ...')
# X with selected features and labels & blanks removed
x_data_features = selected_features[1:,:]
x_data_features[x_data_features == ''] = 0.0
x_data = x_data_features
print('First few Stocks with Features, no Lables: ', '\n', x_data[0:5,:], ' ...')
print(np.size(x_data[:,0]), 'Stocks by', np.size(x_data[0,:]), 'Features')

First few Stocks with Features, no Lables:  
 [['AAPL' '0.07' '87032001731.00' '0.41' '0.22' '194797002476.43'
  '60023999917.99' '0.09' '128249002132.18' '67155000072.65' '-0.02' '0.31'
  '20484000076.70' '0.93']
 ['GOOGL' '0.01' '3938000070.58' '0.41' '0.24' '128635002231.52'
  '22456999936.96' '0.04' '134103000781.74' '83055999197.25' '0.01' '0.18'
  '9405999858.15' '0.97']
 ['MSFT' '0.06' '74690001112.58' '2.41' '0.15' '131134004467.36'
  '19614000366.99' '0.06' '70372001200.19' '136932002561.31' '0.30' '0.15'
  '13928000042.95' '0.99']
 ['XOM' '0.04' '46154999967.93' '0.05' '0.48' '211659003189.18'
  '10297999997.22' '0.00' '170597002584.78' '5093000063.17' '0.08' '0.05'
  '5093000063.17' '0.90']
 ['JNJ' '0.05' '26988999712.38' '0.33' '0.23' '81553000582.14'
  '19682000018.13' '0.04' '72768999735.12' '40432999255.57' '0.18' '0.24'
  '18205000375.04' '0.93']]  ...
1753 Stocks by 14 Features


In [18]:
# Import best performing stocks of 2015 (y = 1)
import csv
data = list(csv.reader(open('../data/y2015.csv')))
y_data = np.asarray(data[1:])
print('First few Positive Examples: ', '\n', y_data[0:3,0:5], ' ...')
# Find X and Y tickers
x_tickers = x_data[:,0]
y_tickers = y_data[:,0]
# Format Y to y = 1 (positive) and y = 0 (negative) examples 
true_false_mask = np.in1d(x_tickers, y_tickers)
y_mask = np.where(true_false_mask,1,0)
print('Positive Example Count: ', np.size(x_tickers[np.nonzero(y_mask)]))
# Place dataset into input (X) and output (Y) variables
x_strings = x_data[:,1:]  # take off tickers, as they can't be tensor'd
X = x_strings.astype(np.float)  # convert strings to float
Y = y_mask        # Y uses the 0, 1 to show negative and positive examples
np.set_printoptions(precision=3, suppress=True)
print('First few X Training Examples with', np.size(X[0,:]) , 'Selected Features: \n', X[0:5,:], ' ...')
# print('First few Y values: ', '\n', Y[0:10].reshape(10,1), ' ...')

First few Positive Examples:  
 [['ALDW' 'Alon USA Partners, LP' 'NYSE' 'Energy' 'Exploration & Production']
 ['AMWD' 'American Woodmark Corp.' 'NASD' 'Industrial' 'Building Materials']
 ['AMZN' 'Amazon.com, Inc.' 'NASD' 'Cyclicals' 'Broadline Retailers']]  ...
Positive Example Count:  61
First few X Training Examples with 13 Selected Features: 
 [[  7.000e-02   8.703e+10   4.100e-01   2.200e-01   1.948e+11   6.002e+10
    9.000e-02   1.282e+11   6.716e+10  -2.000e-02   3.100e-01   2.048e+10
    9.300e-01]
 [  1.000e-02   3.938e+09   4.100e-01   2.400e-01   1.286e+11   2.246e+10
    4.000e-02   1.341e+11   8.306e+10   1.000e-02   1.800e-01   9.406e+09
    9.700e-01]
 [  6.000e-02   7.469e+10   2.410e+00   1.500e-01   1.311e+11   1.961e+10
    6.000e-02   7.037e+10   1.369e+11   3.000e-01   1.500e-01   1.393e+10
    9.900e-01]
 [  4.000e-02   4.615e+10   5.000e-02   4.800e-01   2.117e+11   1.030e+10
    0.000e+00   1.706e+11   5.093e+09   8.000e-02   5.000e-02   5.093e+09
    9.000e-01]

In [19]:
# Feature Extraction with Low Variance Removal
import pandas
from sklearn.feature_selection import VarianceThreshold
# load data
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)
array = dataframe.values
X_pima = array[:,0:8]
# Before Data
np.set_printoptions(precision=3, suppress=True)
print(names)
print('Raw Features: \n', X[0:5,:])
# feature extraction
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
after_features = sel.fit_transform(X_pima)
# summarize selected features
print('After fit_transform() Features: \n', after_features[0:5,:])

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
Raw Features: 
 [[  7.000e-02   8.703e+10   4.100e-01   2.200e-01   1.948e+11   6.002e+10
    9.000e-02   1.282e+11   6.716e+10  -2.000e-02   3.100e-01   2.048e+10
    9.300e-01]
 [  1.000e-02   3.938e+09   4.100e-01   2.400e-01   1.286e+11   2.246e+10
    4.000e-02   1.341e+11   8.306e+10   1.000e-02   1.800e-01   9.406e+09
    9.700e-01]
 [  6.000e-02   7.469e+10   2.410e+00   1.500e-01   1.311e+11   1.961e+10
    6.000e-02   7.037e+10   1.369e+11   3.000e-01   1.500e-01   1.393e+10
    9.900e-01]
 [  4.000e-02   4.615e+10   5.000e-02   4.800e-01   2.117e+11   1.030e+10
    0.000e+00   1.706e+11   5.093e+09   8.000e-02   5.000e-02   5.093e+09
    9.000e-01]
 [  5.000e-02   2.699e+10   3.300e-01   2.300e-01   8.155e+10   1.968e+10
    4.000e-02   7.277e+10   4.043e+10   1.800e-01   2.400e-01   1.821e+10
    9.300e-01]]
After fit_transform() Features: 
 [[   6.   148.    72.    35.     0.    33.6   50. ]
 [   1.  

In [20]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# load data
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)
array = dataframe.values
X_pima = array[:,0:8]
Y_test = array[:,8]
# feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X_pima, Y_test)
# summarize scores
print(names)
np.set_printoptions(precision=3)
print(fit.scores_)
features_test = fit.transform(X_pima)
# summarize selected features
print(features_test[0:5,:])

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
[  111.52   1411.887    17.605    53.108  2175.565   127.669     5.393
   181.304]
[[ 148.     0.    33.6   50. ]
 [  85.     0.    26.6   31. ]
 [ 183.     0.    23.3   32. ]
 [  89.    94.    28.1   21. ]
 [ 137.   168.    43.1   33. ]]


In [31]:
# Feature Extraction with Univariate Statistical Tests (ANOVA F-value f_classif for classification)
# import numpy
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# feature extraction
SelectKBest_features = SelectKBest(score_func=f_classif, k=4)
SelectKBest_fit = SelectKBest_features.fit(X, Y)
# summarize scores
initial_feature_labels = selected_features[0,1:]
np.set_printoptions(precision=3, suppress=True)
print('Initial Feature Names: \n', initial_feature_labels)
print('Fit SCores: \n', SelectKBest_fit.scores_)
SelectKBest_labels = SelectKBest_fit.transform(initial_feature_labels.reshape(1, -1))
SelectKBest_output_features = SelectKBest_fit.transform(X)
# summarize selected features
print('Selected Feature Labels: \n', SelectKBest_labels)
print('Selected Features: \n', SelectKBest_output_features[0:5,:])
print('Orginal Features: \n', X[0:5,:])

Initial Feature Names: 
 ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'
 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum']
Fit SCores: 
 [ 11.411   1.563   0.065   7.142   0.343   0.018   3.119   0.014   1.039
   0.032   0.013   0.306   0.565]
Selected Feature Labels: 
 [['total yield' 'ms debt' 'book price' 'fcf yield']]
Selected Features: 
 [[  7.000e-02   8.703e+10   2.200e-01   9.000e-02]
 [  1.000e-02   3.938e+09   2.400e-01   4.000e-02]
 [  6.000e-02   7.469e+10   1.500e-01   6.000e-02]
 [  4.000e-02   4.615e+10   4.800e-01   0.000e+00]
 [  5.000e-02   2.699e+10   2.300e-01   4.000e-02]]
Orginal Features: 
 [[  7.000e-02   8.703e+10   4.100e-01   2.200e-01   1.948e+11   6.002e+10
    9.000e-02   1.282e+11   6.716e+10  -2.000e-02   3.100e-01   2.048e+10
    9.300e-01]
 [  1.000e-02   3.938e+09   4.100e-01   2.400e-01   1.286e+11   2.246e+10
    4.000e-02   1.341e+11   8.306e+10   1.000e-02   1.800e-01   9.406e+09
    9.700e-01]
 [  6.

In [32]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# feature extraction
chi_select_features = SelectKBest(score_func=chi2, k=4)
non_z = np.where(X < 0)
x_no_neg = np.copy(X)
x_no_neg[x_no_neg < 0] = 0.0
chi_fit = chi_select_features.fit(x_no_neg, Y)
# summarize scores
initial_feature_labels = selected_features[0,1:]
print('Initial Feature Names: \n', initial_feature_labels)
np.set_printoptions(precision=3, suppress=True)
print('Chi-Fit Scores: \n', chi_fit.scores_)
chi_labels = chi_fit.transform(initial_feature_labels.reshape(1, -1))
chi_fit_output_features = chi_fit.transform(X)

# summarize selected features
print('Selected Feature Labels: \n', chi_labels)
print('Selected Features: \n', chi_fit_output_features[0:5,:])
print('Orginal Features: \n', X[0:5,:])

Initial Feature Names: 
 ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'
 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum']
Chi-Fit Scores: 
 [  5.792e-01   1.220e+11   2.894e-01   4.409e+00   3.067e+10   1.387e+08
   3.710e-01   5.918e+08   3.363e+10   1.813e+02   4.006e-04   3.300e+10
   1.113e-02]
Selected Feature Labels: 
 [['ms debt' 'sic' 'ms cem' 'ms ce']]
Selected Features: 
 [[  8.703e+10   1.948e+11   6.716e+10   2.048e+10]
 [  3.938e+09   1.286e+11   8.306e+10   9.406e+09]
 [  7.469e+10   1.311e+11   1.369e+11   1.393e+10]
 [  4.615e+10   2.117e+11   5.093e+09   5.093e+09]
 [  2.699e+10   8.155e+10   4.043e+10   1.821e+10]]
Orginal Features: 
 [[  7.000e-02   8.703e+10   4.100e-01   2.200e-01   1.948e+11   6.002e+10
    9.000e-02   1.282e+11   6.716e+10  -2.000e-02   3.100e-01   2.048e+10
    9.300e-01]
 [  1.000e-02   3.938e+09   4.100e-01   2.400e-01   1.286e+11   2.246e+10
    4.000e-02   1.341e+11   8.306e+10   1.000e-02   1.

In [41]:
# Feature Extraction with RFE
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# feature extraction
rfe_model = LogisticRegression()
rfe = RFE(rfe_model, 3)
rfe_fit = rfe.fit(X, Y)

# summarize scores
initial_feature_labels = selected_features[0,1:]
print('Initial Feature Names: \n', initial_feature_labels)
np.set_printoptions(precision=3, suppress=True)
print("Num Features: ", rfe_fit.n_features_)
print("Selected Features: ", rfe_fit.support_)
print("Feature Ranking: ", rfe_fit.ranking_)
rfe_labels = rfe_fit.transform(initial_feature_labels.reshape(1, -1))
rfe_fit_output_features = chi_fit.transform(X)

# summarize selected features
print('Selected Feature Labels: \n', rfe_labels)
print('Selected Features: \n', rfe_fit_output_features[0:5,:])
print('Orginal Features: \n', X[0:5,:])

Initial Feature Names: 
 ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'
 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum']
Num Features:  3
Selected Features:  [False  True False False False False False False  True False False  True
 False]
Feature Ranking:  [10  1  8  7  4  2 11  3  1  5  9  1  6]
Selected Feature Labels: 
 [['ms debt' 'ms cem' 'ms ce']]
Selected Features: 
 [[  8.703e+10   1.948e+11   6.716e+10   2.048e+10]
 [  3.938e+09   1.286e+11   8.306e+10   9.406e+09]
 [  7.469e+10   1.311e+11   1.369e+11   1.393e+10]
 [  4.615e+10   2.117e+11   5.093e+09   5.093e+09]
 [  2.699e+10   8.155e+10   4.043e+10   1.821e+10]]
Orginal Features: 
 [[  7.000e-02   8.703e+10   4.100e-01   2.200e-01   1.948e+11   6.002e+10
    9.000e-02   1.282e+11   6.716e+10  -2.000e-02   3.100e-01   2.048e+10
    9.300e-01]
 [  1.000e-02   3.938e+09   4.100e-01   2.400e-01   1.286e+11   2.246e+10
    4.000e-02   1.341e+11   8.306e+10   1.000e-02   1.800e-01

In [43]:
# Feature Importance with Extra Trees Classifier
from sklearn.ensemble import ExtraTreesClassifier
# load data
tree_X = X
# feature extraction
initial_feature_labels = selected_features[0,1:]
print('Initial Feature Names: \n', initial_feature_labels)
tree_model = ExtraTreesClassifier()
tree_model.fit(tree_X, Y)
print(tree_model.feature_importances_)

Initial Feature Names: 
 ['total yield' 'ms debt' 'roic v2' 'book price' 'sic' 'opInc' 'fcf yield'
 'comStockEq' 'ms cem' 'total return' 'spitz roic' 'ms ce' 'momentum']
[ 0.072  0.067  0.089  0.069  0.076  0.074  0.072  0.085  0.064  0.092
  0.074  0.08   0.086]
